# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Henrique Melanda - Front-End Developer
email: hjdesigner23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um Blog de um desenvolvedor apaixonado por front-end, CSS evangelista, rock, viagens, moto, livros, fotografia e animais.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://henriquemelanda.com.br" # the base hostname & protocol for your site
twitter: https://www.twitter.com/coisadedev
github:  https://www.github.com/hjdesigner
facebook: https://www.facebook.com/hjFrontEnd
codepen: https://codepen.io/hjdesigner/
linkedin: https://br.linkedin.com/in/coisadedev

# Build settings
markdown: kramdown

permalink: /:title

sass:
  style: compressed

links:
  - title: Sobre
    url: /
  - title: Blog
    url: /blog
  - title: Projetos
    url: /projetos
  - title: Labs
    url: /labs
